# Generated by Django 5.2.5 on 2025-09-15 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment_is_public_alter_comment_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_email",
            field=models.EmailField(
                default="unknown@example.com",
                max_length=254,
                verbose_name="작성자 이메일",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author_name",
            field=models.CharField(
                default="Unknown", max_length=150, verbose_name="작성자 이름"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="댓글 작성자",
            ),
        ),
    ]
